### ISSUE TITLE
When enter letters, there is staying previous styles ) We should remove it ))

### ISSUE THREAD

**Issue by udilbar** [malikabakhtiyorova/temperature-converter#1]
![Screenshot_4](https://user-images.githubusercontent.com/68459485/98547908-ab695300-22ba-11eb-8115-d7e2a89cf5e0.png)
For example, when I entered 0, background color of result input has changed to blue. And then when I entered some letters, the background color wasn't removed

**Comment by malikabakhtiyorova** [comment]
Fixed!
